<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>a</string>
		<string>s</string>
	</array>
	<key>name</key>
	<string>6502 ACME Assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(adc|and|asl|bit|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|sbc|sec|sed|sei|sta|stx|sty|tax|txa|tay|tya|tsx|txs)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>not officially supported opcodes</string>
			<key>match</key>
			<string>\b(slo|rla|sre|rra|sax|lax|dcp|isc|anc|asr|arr|sbx|dop|top|jam)\b</string>
			<key>name</key>
			<string>keyword.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bcc|bcs|beq|bmi|bne|bpl|brk|bvc|bvs|jmp|jsr|rti|rts)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!(08|by|byte|wo|word|24|32|fi|fill|align)\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!(cpu)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!(if|ifdef|for|set|do|warn|error|serious|endoffile)\b</string>
			<key>name</key>
			<string>meta.preprocessor.flow-control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!(binary|bin)\b</string>
			<key>name</key>
			<string>meta.preprocessor.io</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.io.output</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.untitled</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.io.format</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\!to)\s*(\"[^"]+\")\s*,\s*([a-zA-Z]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.io.input</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.library.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\!source|\!src)\s*([\"&lt;][^\"&gt;]+[\"&gt;])</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Za-z_][A-Za-z0-9_]+</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^([+]+|[-]+)</string>
			<key>name</key>
			<string>entity.name.label.local</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\%[01#.]+</string>
			<key>name</key>
			<string>constant.numeric.bin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&amp;[0-7]+</string>
			<key>name</key>
			<string>constant.numeric.oct</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.6502.acme</string>
	<key>uuid</key>
	<string>858A6704-233B-4518-87DD-3CAF7762E85B</string>
</dict>
</plist>
